apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: devops
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 8080
    targetPort: 3000
  - name: gitea-ssh
    port: 22
    targetPort: 22
  type: LoadBalancer