apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  namespace: devops
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: kunde21/gitea-arm:latest
        ports:
        - containerPort: 3000
        - containerPort: 22
        volumeMounts:
        - mountPath: /data
          name: git-data
      volumes:
      - name: git-data
        persistentVolumeClaim:
          claimName: devops-storage